package com.neelastack.lakhdatar.service;
import com.neelastack.lakhdatar.config.AppProperties; import com.neelastack.lakhdatar.domain.*; import com.neelastack.lakhdatar.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.boot.CommandLineRunner; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;
import java.time.Instant; import java.time.ZoneId; import java.time.ZonedDateTime;
@Component @RequiredArgsConstructor
public class BootstrapData implements CommandLineRunner {
 private final AppProperties props; private final UserRepository users; private final OrganizerRepository organizers; private final OrganizerMemberRepository members; private final VenueRepository venues; private final BrandConfigurationRepository brands; private final EventRepository events; private final TicketTypeRepository ticketTypes; private final PasswordEncoder encoder;
 @Override @Transactional public void run(String... args){if(props.bootstrap()==null||!props.bootstrap().enabled())return; seed();}
 void seed(){String email=props.bootstrap().adminEmail(); if(email==null||props.bootstrap().adminPassword()==null||props.bootstrap().adminPassword().length()<12)throw new IllegalStateException("Bootstrap admin credentials are invalid"); User admin=users.findByEmailIgnoreCase(email).orElse(null);
  if(admin==null){User u=new User();u.setEmail(email.toLowerCase());u.setFullName(props.bootstrap().adminName());u.setPasswordHash(encoder.encode(props.bootstrap().adminPassword()));u.setRole(Enums.UserRole.ADMIN);u.setEnabled(true);admin=users.save(u);}
  else if(admin.getRole()!=Enums.UserRole.ADMIN || !admin.isEnabled()) throw new IllegalStateException("Bootstrap admin email belongs to a non-admin or disabled account; refusing to modify it");
  Organizer org=organizers.findBySlug(props.bootstrap().organizerSlug()).orElseGet(()->{Organizer o=new Organizer();o.setName(props.bootstrap().organizerName());o.setSlug(props.bootstrap().organizerSlug());o.setLogoUrl("/assets/lakhdatar-logo.svg");o.setDescription("Lakhdatar Events curates and produces live cultural experiences. Tickets are sold through the Neelastack event platform.");return organizers.save(o);}); if(!members.existsByOrganizerIdAndUserId(org.getId(),admin.getId())){OrganizerMember m=new OrganizerMember();m.setOrganizerId(org.getId());m.setUserId(admin.getId());m.setRole("OWNER");members.save(m);} var existingEvent=events.findBySlug(props.bootstrap().eventSlug());
  if(existingEvent.isPresent()){ if(!existingEvent.get().getOrganizerId().equals(org.getId())) throw new IllegalStateException("Bootstrap event slug belongs to another organizer"); return; }
  Venue v=new Venue();v.setOrganizerId(org.getId());v.setName("Rajasthan Celebration Lawn");v.setAddress("Jaipur, Rajasthan");v.setCity("Jaipur");v.setState("Rajasthan");venues.save(v); BrandConfiguration b=new BrandConfiguration();b.setScope("EVENT");b.setOrganizerId(org.getId());b.setOrganizerName(org.getName());b.setOrganizerLogoUrl("/assets/lakhdatar-logo.svg");b.setPrimaryBrandColor("#D7A548");b.setSecondaryBrandColor("#711D40");b.setTechnologyPartnerEnabled(true);b.setTechnologyPartnerName("Neelastack");b.setTechnologyPartnerLogoUrl("/assets/neelastack-logo.svg");b.setTechnologyPartnerUrl(props.branding().neelastackPublicUrl());b.setPromoEnabled(true);b.setPromoTitle("Build your next digital experience");b.setPromoDescription("Premium web applications, portals, dashboards and automation for modern businesses.");b.setPromoCtaText("Explore Neelastack");b.setPromoCtaUrl(props.branding().neelastackPublicUrl());brands.save(b);
  Event e=new Event();e.setSlug(props.bootstrap().eventSlug());e.setName("Dandiya Night 2026");e.setDescription("An evening of colour, music and dandiya in Jaipur. Bring your friends, dress festive and celebrate together.");e.setStartsAt(ZonedDateTime.of(2026,10,12,19,0,0,0,ZoneId.of("Asia/Kolkata")).toInstant());e.setEndsAt(ZonedDateTime.of(2026,10,12,23,30,0,0,ZoneId.of("Asia/Kolkata")).toInstant());e.setCapacity(5000);e.setShortDescription("An evening of colour, music and dandiya in Jaipur.");e.setCategory("Festival");e.setFeatured(true);e.setPublishedAt(java.time.Instant.now());e.setHighlights("Live dandiya floor\nFood and festive stalls\nSecure QR entry");e.setStatus(Enums.EventStatus.PUBLISHED);e.setCurrency("INR");e.setOrganizerId(org.getId());e.setVenueId(v.getId());e.setBrandConfigId(b.getId());e=events.save(e);
  saveType(e, "General Entry", "Open access to the main Dandiya floor.", 59900, 3000, 1, 10); saveType(e,"VIP Entry","Priority entry and premium zone access.",99900,1500,1,8); saveType(e,"Couple Pass","Entry for two guests.",149900,500,1,5);
 }
 private void saveType(Event e,String name,String desc,long price,int qty,int min,int max){TicketType t=new TicketType();t.setEventId(e.getId());t.setName(name);t.setDescription(desc);t.setPriceMinorUnits(price);t.setCurrency("INR");t.setTotalQuantity(qty);t.setMinPerOrder(min);t.setMaxPerOrder(max);t.setStatus(Enums.TicketTypeStatus.ACTIVE);ticketTypes.save(t);}
}
