package com.neelastack.lakhdatar.service;

import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Base64;

/** Generates the canonical ticket PDF server-side. No customer bearer token is ever embedded in the PDF. */
@Service
@RequiredArgsConstructor
public class TicketPdfService {
    private final TicketQueryService tickets;

    public byte[] generate(java.util.UUID ticketId, String token) {
        TicketQueryService.TicketView t = tickets.get(ticketId, token);
        try (PDDocument doc = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);
            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                final PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
                final PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                final PDType1Font italic = new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE);
                float w = page.getMediaBox().getWidth();
                float margin = 42f;
                float y = page.getMediaBox().getHeight() - margin;

                setNonStrokingRgb(cs, 24, 19, 27);
                cs.addRect(0, page.getMediaBox().getHeight() - 92, w, 92);
                cs.fill();

                text(cs, bold, 20, margin, y - 8, safe(t.brand().organizerName(), "Neelastack Events"));
                text(cs, regular, 10, margin, y - 28, "Digital admission pass");

                float contentY = y - 125;
                text(cs, bold, 24, margin, contentY, safe(t.eventName(), "Event"));
                text(cs, regular, 11, margin, contentY - 24,
                        "Ticket " + safe(t.ticketNumber(), "") + " · " + t.ticketPosition() + " of " + t.orderTicketCount());
                text(cs, bold, 10, margin, contentY - 42,
                        t.orderTicketCount() + " " + (t.orderTicketCount() == 1 ? "seat" : "seats") + " booked in this order");
                text(cs, bold, 12, margin, contentY - 66,
                        safe(t.ticketType(), "Ticket"));
                text(cs, regular, 12, margin, contentY - 92,
                        "Attendee: " + safe(t.attendeeName(), "Guest"));
                text(cs, regular, 10, margin, contentY - 117,
                        "Starts: " + t.startsAt());
                if (t.venueName() != null) {
                    text(cs, regular, 10, margin, contentY - 142,
                            "Venue: " + safe(t.venueName(), "Venue"));
                }
                if (t.venueAddress() != null) {
                    text(cs, regular, 9, margin, contentY - 162,
                            "Address: " + safe(t.venueAddress(), ""));
                }

                byte[] qrBytes = decodeQr(t.qrDataUri());
                if (qrBytes == null || qrBytes.length == 0) {
                    throw new IllegalStateException("Ticket QR image is missing or invalid");
                }
                // QR data is generated by the server as a PNG data URI. Let PDFBox detect the
                // image content directly instead of decoding through AWT/ImageIO first. This is
                // deterministic in a headless container and avoids image-type/color-model edge cases.
                PDImageXObject qrImage = PDImageXObject.createFromByteArray(doc, qrBytes, "ticket-qr.png");
                float size = 190f;
                cs.drawImage(qrImage, w - margin - size, contentY - 170, size, size);
                text(cs, regular, 9, w - margin - size, contentY - 183, "Present this QR at the gate");

                setStrokingRgb(cs, 220, 213, 205);
                cs.moveTo(margin, 185);
                cs.lineTo(w - margin, 185);
                cs.stroke();
                text(cs, regular, 9, margin, 164,
                        "Status: " + safe(t.status(), "ISSUED"));
                text(cs, regular, 9, margin, 148,
                        "Source: " + safe(t.source(), "ONLINE_PAYMENT"));
                text(cs, regular, 9, margin, 132,
                        "Technology partner: " + safe(t.brand().technologyPartnerName(), "Neelastack"));
                text(cs, italic, 8, margin, 88,
                        "Keep this pass available on your phone. Admission is subject to event rules and ticket validity.");
            }
            doc.save(out);
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Ticket PDF generation failed", ex);
        }
    }

    /**
     * Applies an RGB color using PDFBox's normalized 0..1 component contract.
     * Keeping the conversion here prevents accidental use of 0..255 values with
     * the float overloads, which would fail at runtime in PDFBox 3.x.
     */
    private static void setNonStrokingRgb(PDPageContentStream cs, int red, int green, int blue) throws IOException {
        cs.setNonStrokingColor(normalizeColorComponent(red), normalizeColorComponent(green),
                normalizeColorComponent(blue));
    }

    private static void setStrokingRgb(PDPageContentStream cs, int red, int green, int blue) throws IOException {
        cs.setStrokingColor(normalizeColorComponent(red), normalizeColorComponent(green),
                normalizeColorComponent(blue));
    }

    private static float normalizeColorComponent(int component) {
        if (component < 0 || component > 255) {
            throw new IllegalArgumentException("RGB component must be within 0..255");
        }
        return component / 255f;
    }

    private static void text(PDPageContentStream cs, PDType1Font font, float size, float x, float y, String value) throws IOException {
        cs.beginText(); cs.setFont(font, size); cs.newLineAtOffset(x, y); cs.showText(ascii(value)); cs.endText();
    }

    private static byte[] decodeQr(String dataUri) {
        if (dataUri == null) return null;
        int comma = dataUri.indexOf(',');
        if (comma < 0) return null;
        try { return Base64.getDecoder().decode(dataUri.substring(comma + 1)); }
        catch (IllegalArgumentException ignored) { return null; }
    }

    private static String safe(String value, String fallback) { return value == null || value.isBlank() ? fallback : value; }

    /** Standard 14 fonts are intentionally used so the PDF has no external-font deployment dependency. */
    private static String ascii(String value) {
        if (value == null) return "";
        return value.replace("₹", "INR ").replaceAll("[^\\x20-\\x7E]", "?");
    }
}
